
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - chmod +x mvnw

services:
  - docker

addons:
  sonarcloud:
    organization: "kamil-bednarczyk-github"
    token:
      secure: "$SONAR_TOKEN"

script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


after_success:
  - mvn dockerfile:build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push kamilbednarczyk/user_service