version: "2"
services:
  user_service:
    image: kamilbednarczyk/user_service:latest
    container_name: user_service
    ports:
      - 8092:8092
    depends_on:
      - mongodb
      - rabbit
    environment:
      spring.rabbitmq.host: rabbit
      spring.data.mongodb.host: mongodb
      security.oauth2.resource.token-info-uri: http://user_service:8092/oauth/check_token
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      eureka.instance.preferIpAdress: "true"
    links:
      - mongodb
      - rabbit
      - eureka
    networks:
      - spring-cloud-network
  events_service:
    image: kamilbednarczyk/events_service:latest
    container_name: events_service
    ports:
      - 8091:8091
    depends_on:
      - mongodb
      - rabbit
    environment:
      spring.rabbitmq.host: rabbit
      eureka.instance.preferIpAdress: "true"
      spring.data.mongodb.host: mongodb
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      security.oauth2.resource.token-info-uri: http://user_service:8092/oauth/check_token
    links:
      - rabbit
      - eureka
      - mongodb
      - user_service
    networks:
      - spring-cloud-network
  team_service:
    image: kamilbednarczyk/team_service:latest
    container_name: team_service
    ports:
      - 8094:8094
    depends_on:
      - mongodb
      - rabbit
    environment:
      spring.rabbitmq.host: rabbit
      eureka.instance.preferIpAdress: "true"
      spring.data.mongodb.host: mongodb
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      security.oauth2.resource.token-info-uri: http://user_service:8092/oauth/check_token
    networks:
      - spring-cloud-network
    links:
      - rabbit
      - mongodb
      - eureka
      - user_service
  eureka:
    container_name: eureka
    image: kamilbednarczyk/eureka_service:latest
    ports:
      - 8761:8761
    environment:
      eureka.instance.hostname: eureka
    networks:
      - spring-cloud-network
  frontend:
    container_name: frontend
    image: kamilbednarczyk/squad-agenda-frontend
    ports:
      - 8800:80
    networks:
      - spring-cloud-network
# dependency services
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: agenda
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - spring-cloud-network
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge

