spring:
  application:
    name: user-service
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  kafka:
      bootstrap-servers: localhost:9092
      topic:
        userCreated: USER_CREATED_TOPIC
  security:
    basic:
      enabled: false