spring:
  application:
    name: user-service
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: agenda

security:
  oauth2:
    client:
      client-id: kassad
      client-secret: kassad

mail:
  username: <username>
  password: <password>