spring:
  application:
    name: user-service
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      client-id: kassad
      client-secret: kassad

mail:
  username:
  password: