spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: agenda
 # rabbitmq:
 #   host: rabbit

  mvc:
    dispatch-options-request: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      client-id: kassad
      client-secret: kassad
#      authorized-grant-types: authorization_code,refresh_token,password

mail:
  host: smtp.gmail.com
  port: 465
  username: <username>
  password: <password>
  smtp:
    ssl:
      enable: true

logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
        data:
          mongodb:
            core:
              MongoTemplate: INFO