spring:
  application:
    name: user-service
  kafka:
    key:
      userUpdated: 1231231231
    consumer:
      auto-offset-reset: earliest
      group-id: 1123122
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
kafka:
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
      userUpdated: USER_UPDATED_TOPIC
security:
  basic:
    enabled: false