spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: agenda
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      client-id: kassad
      client-secret: kassad # $2a$08$kU3H5uvRJlZ2UvcaFpi5GOriMuBtp3.VR8luvgYJ6c5F.I5mQpZFS

mail:
  host: smtp.gmail.com
  port: 465
  username: <username>
  password: <password>
